### ISSUE TITLE
FOM Keycloak/bceid issue

### ISSUE THREAD

**Issue by explorertolu** [bcgov/nr-fom#245] opened 2022-09-13 17:10 UTC
Onboarding West Fraser BCEID users not working.

Issue:
A batch of users from West Fraser are having issue login to FOM admin (https://fom.nrs.gov.bc.ca/admin) with their BCeID accounts.
User list:
   Jade Laramie
   Mike Sakakibara
   Kristie Seaborn
   Ben Barker (already successful!)
   Michele Enright
   Aaron Hames
   Guohua Li
   Lars Lu
   Jaret van der Griessen

So far only "Ben" (and one other) succeed.

**Comment by ianliuwk1019** [comment] 2022-09-13 20:50
Verified with Derek using newly created BCeID test account and was able to successfully login to FOM.
The flow/process does not seem to be the problem and also doe not appear to be the problem on FOM application side.

Once after the registered Business BCeID user first login and shows up on KeyCloak (Derek did the intermediate steps, searched and verified on KeyCloak for the user), the user's subsequent login will be successful to FOM.

All government test BCeID accounts are working. Also "Ben" is good as well. 
The problem seems to be pointing towards BCeID setup.
Derek/Gbola will contact West Fraser BCEID admin person to verify some settings with users' BCeID.

**Comment by basilv** [comment] 2022-09-21 18:13
Confirmed not an issue with FOM. Same behavior observed with other application. Believed to be an issue with keycloak, or with the communication between BCeID and keycloak. Keeping open until addressed.

Confirmed with end user two issues:
1. Failure of new user getting registered in keycloak. (Just get redirected back to login.)
2. Redirect back to login - after successful BCeID login, the login page redisplays. They do not proceed to keycloak (no session established) nor FOM. 

I believe both issues have the same root cause - keycloak is not receiving or not accepting the BCeID token and just redirecting them back to log in again. Plan is to test this by looking at network tab.

**Comment by basilv** [comment] 2022-09-22 15:37
Network tab shows that traffic isn't leaving the CLP (common login page). Marco suspects the WAM servers.

**Comment by basilv** [comment] 2022-10-11 17:10
Discovered that West Fraser users can register and access FOM when they are not on their corporate network, so this strongly suggests that the issue is with their corporate network security. Workaround for impacted users is to connect from a non-corporate network. Further troubleshooting needs the West Fraser corporate network team plus Keycloak and/or WAM. Nothing for FOM to do, so closing.

**Closed as completed by basilv** 2022-10-11 17:10 UTC
