### ISSUE TITLE
Upgrade to Angular 15 and more recent Node

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#158] opened 2022-07-19 17:20 UTC
Upgrade both front-ends to latest stable release of Angular (15?). Likely want to upgrade to Node 16+ for all projects.

SCOPE: DEV only

**Comment by ianliuwk1019** [comment] 2023-04-10 21:42
The latest stable node.js is v18.15.0.
Although FAM is running at v16, for this upgrade, maybe we can target to v18 first.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/c8c4ccc8-72d9-4adf-abdb-b9f3547759d0)

And it should be good with Angular V15.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/d137cf36-5711-4f07-a6c4-cab5d53c511a)

**Comment by DerekRoberts** [comment] 2023-04-10 23:08
I'm pretty sure 16 to 18 introduced a breaking change. (18 to 18.5 won't make a big difference.) Maybe estimate this one a little higher?

**Comment by ianliuwk1019** [comment] 2023-04-26 16:40
Current running FOM (main):
   - Running environment: **Node v14.**
   - Frontend (public/admin): **Angular v11.**
   - Backend (api): **NestJS v7.**

Upgrade target:
   - Running environment: **Node v18.**
   - Frontend (public/admin): **Angular v15. toward v16 ?**
   - Backend (api): **NestJS v9.**

**Comment by ianliuwk1019** [comment] 2023-04-26 16:54
Current Progress:
* Frontend:
   - Migration plan: 
      "**public**" component upgrade to Angular **v12** first. (**done**, app stands up and verified locally)
      "**admin**" component - will wait for "public" component to be done for upgrade to **v15** then we will do it in one jump.
```
```

* Backend:
   -  "**api**" component upgrade NestJS to **v9** with running on Node **v18**. (**done, app stands up and verified locally**)
         - There is minor warning from package `**@openapitools/openapi-generator-cli**`. Seems that the package hasn't been keeping up with NestJS v9 switching to axio version yet. However, expect this not to impact the app.

**Comment by ianliuwk1019** [comment] 2023-05-02 19:53
Will try to include ticket #146 (`angularCompilerOptions' to set "strictTemplates": true) together with 'admin' component upgrade.
Currently when enable, admin will have many compilation errors, mostly on the html templates. Code fix will be needed.

**Comment by ianliuwk1019** [comment] 2023-05-04 21:06
Link enhancement ticket #346 to this ticket. Planning to figure this out after migrating to Angular 15.

**Comment by ianliuwk1019** [comment] 2023-05-08 18:48
Migrate both public/admin frontend to **Angular 15**; but it is only the first step to just bump the dependencies up and make sure it builds PROD successfully and tests passing. Still few issues after serving up for frontends. Other than some layout issues (missing dropdown icon, margin/padding not looking the same), leaflet images issue (not major), aws warnings, and some few minor issues, the two main major tasks with this migration will be dealt soon after issue for backend 403 returns to authenticated users (aws enabled):
- **Angular typed Form**.
- **Angular standalone component**.
These two above will assume to take a bit time and require app to be verified (run through all pages) in detail.

Initial deployment to Openshift environment with branch `feat/158-Node-Angular-upgrade--node18-api-v9-public-admin-angular15`, pipeline passing and deployed successfully with:
- Node **v18**,
- NestJS **v9** (api)
- Angular **v15** (public/admin)

When trying out 'adimn' (from **Openshift** deployment frontend instance), through FAM authenticated/authorization, the token retrieval, token parsing to user object, and token refreshing seem to be good. However, user still keep getting `403 error` from backend api. Will need to investigate this major issue before moving on to all the rest.

**Comment by ianliuwk1019** [comment] 2023-05-08 22:34
After investigating api backend, turns out backend code is fine (when NestJs controller is called), the problem is that current `AuthInterceptor' is **no longer working**. This file hasn't been changed since year 2022 (well before FOM switching to FAM with Cognito).

After migration from NestJS v7 to v9, NestJS has changed its **internal behavior** and affects how this custom `AuthInterceptor` working. Can't seem to find NestJS migration guide mentions anything related to behavior of the interceptor.
The `@UserHeader` and `@UserRequiredHeader` declarators (used by NestJS controllers) are also not working because of the interceptor. So these two declarators always return `undefined` for the controller by this code `@UserHeader() user: User,` for example. And that's why it is always getting **403 errors** (if the endpoints requires auth user) because the **`user` object is missing** for the two declarators.

For some reason, prior to NestJS v8, the usage of `NestInterceptor` was working but I feel now NestJS enforce some internal logic, so to solve this issue we can switch to use [**NestJS Guards**](https://docs.nestjs.com/guards), which is more appropriate for the controllers, similar to Angular Guards.
I quickly experiment on that and is working, will refactor controller to use 'guard' instead for the implementation of validating auth token and parsing to user object (like the purpose of previous `AuthInterceptor`).
@basilv

**Comment by basilv** [comment] 2023-05-09 12:52
Good investigation, let me know when ready to review.

**Comment by DerekRoberts** [comment] 2023-05-09 16:22
Good work @ianliuwk1019!  I look forwarding to see where this goes.  :)

**Comment by ianliuwk1019** [comment] 2023-05-12 15:06
Finished fixing 403 error by replacing previous interceptor implementation with NestJS Guard implementation and adjusted every backend controller.
Moving toward frontend Angular upgrade v15 migration to standalone components.

**Comment by ianliuwk1019** [comment] 2023-05-24 17:58
Code merged to 'main' and deployed to Test environment waiting for uat testing.

**Comment by gormless87** [comment] 2023-06-05 21:48
@amee99073 - please add any comments related to your FOM testing on this issue (#158)

**Comment by amee99073** [comment] 2023-06-05 22:50
**Issue 1**
If I save info on a stakeholder engagement, then make another one, then go back to the previous one and change anything in the Description field, I get the following error :
 Bad Request
The request was not valid: Engagement Date should be on or after commenting start date.
Please fix the issue and try again.

It saved just fine a moment before and the Engagement Date is definitely on the commenting open date; 
https://fom-test.nrs.gov.bc.ca/admin/interactions/100296 
Happened with all 3 stakeholder engagements on that FOM

NOTE
This happens if I try to do anything to a stakeholder engagement after saving it once.  (also note – the date is today’s date – I can’t actually save it for anything later than that – it also saved just fine the first time around without complaint)
I tried to add a file to this one after saving without one and got the same error :
The request was not valid. Engagement Date should be on or after commenting start date. Please fix the issue and try again
https://fom-test.nrs.gov.bc.ca/admin/interactions/100297 

 **Issue 2**
Steps to reproduce :
1.	Create a new FOM
2.	Click on the New Public notice button
3.	It dovetails here – 
a.	Select one of the available years in the pop up, press save
b.	Open the public notice again – the end of operations is blank
c.	Select a year for it again, press save
d.	The following error appears
i.	 Forbidden. You were not authorized to perform the request. Please try again. If this issue persists, try logging out and bck in. If this sill persists, please contact the service desk.
e.	OR
Manually enter a year that falls outside of the year span available.
i.	Originally, this field wasn’t supposed to allow for manual entry in order to keep users from entering values outside of the acceptable range. It is allowing manual entry – well outside of the acceptable range.
f.	Save that incorrect year. It appears to be saved – but if you close and reopen the screen, the value is still blank. Try to save again and the error above appears again
If you then look at the public side, the saved year that was outside of the acceptable range displays on the Public Notice

**Closed as completed** 2023-06-07 04:35 UTC
Labels: enhancement
